output_dir: data/pipeline
images: data/images

os: intel
cran_url: http://cran.us.r-project.org
use_gpu: false

dataset_meta: configs/datasets.tsv
schema_file: configs/schema_mapping_tier1.tsv


defaults:

  preprocessing:
    raw_counts: X
    normalize:
      target_sum: 10_000
    highly_variable_genes:
      n_top_genes: 2000
      batch_key: dataset
      dask: false
    assemble:
      - normalize
      - highly_variable_genes
    colors:
      - dataset
      - cell_type
      - batch_integration
      - age
      - disease

  integration:
    batch: batch_integration
    label: cell_type
    raw_counts: layers/counts
    norm_counts: layers/normcounts
    var_mask:
      - highly_variable
    neighbors:
      n_neighbors: 100
    output_types:
      - embed
    umap_colors:
      - assay
      - dataset
      - study
      - ann_level_1
      - ann_level_2
      - ann_level_3
      - original_ann_level_1
      - original_ann_level_2
      - original_ann_level_3
      - ann_finest_level
      - manual_ann
      - scanvi_label
      - majority_reference
      - qc_status
      - lung_condition
      - sex
      - scrublet_score
      - n_genes
      - n_counts
      - percent_mito
    methods:
      unintegrated:
      harmony_pytorch:
        n_comps: 50
        scale: false
      scvi:
        n_layers: 2
        n_latent: 30
        encode_covariates: True
        deeply_inject_covariates: False
        use_layer_norm: both
        use_batch_norm: none
        gene_likelihood: nb
        max_epochs: 100
        early_stopping: true
      scanvi:
        n_layers: 2
        n_latent: 30
        encode_covariates: True
        deeply_inject_covariates: False
        use_layer_norm: both
        use_batch_norm: none
        gene_likelihood: nb
        max_epochs: 100
        early_stopping: true

  clustering:
    algorithm: leiden
    use_gpu: false
    neighbors:
      use_rep: X_emb
      n_neighbors: 100
      metric: euclidean
    resolutions:
      - 0.5
    hierarchy:
      2: 0.2
      3: 0.5
    umap_colors:
      - assay
      - dataset
      - study
      - ann_level_1
      - ann_level_2
      - ann_level_3
      - original_ann_level_1
      - original_ann_level_2
      - original_ann_level_3
      - ann_finest_level
      - manual_ann
      - scanvi_label
      - majority_reference
      - qc_status
      - lung_condition
      - sex
      - scrublet_score
      - n_genes
      - n_counts
      - percent_mito

  metrics:
    unintegrated: layers/normcounts
    raw_counts: layers/counts
    var_mask: highly_variable
    # overwrite_file_id: true
    weight_batch: 0.4
    label: scanvi_label
    batch:
      - dataset
      # - assay
    gene_sets:
      Immune:
        - CD53
        - PTPRC
        - CORO1A
      Alveolar Mph:
        - CYP27A1
        - MARCO
        - FABP4
      T reg:
        - FOXP3
        - RTKN2
      Epithelial:
        - FXYD3
        - EPCAM
        - ELF3
      pre-TB secretory:
        - SCGB1A1 # from Tata paper
        - SFTPB
        - SCGB3A2
        - RNASE1
        - SFTA1P
      AT0:
        - SFTPB
        - SCGB3A2
        - IGFBP2
        - SERPINF1
        - TSPAN1
        - SFTA2
        - C11orf96
      EC:
        - CLDN5
        - ECSCR
        - CLEC14A
      Stroma:
        - COL1A2
        - DCN
        - MFAP4
      Hematopoietic stem cells:
        - CD53
        - PTPRC
        - CORO1A
        - CRHBP
        - SERPINE2
        - MAP7
    metrics:
      - nmi
      - ari
      # - asw_label
      # - asw_batch
      - cell_cycle
      - clisi
      - ilisi
      - graph_connectivity
      - isolated_label_f1
      - pcr_comparison
      - morans_i_genes
      # - pcr
      # - pcr_genes
      - kbet_pg
  
  marker_genes:
    sample: subject_ID
    groups:
      - majority_reference
      - manual_ann
      - leiden_0.5_2
    marker_genes: HLCA_immune, HLCA_epithelial, HLCA_endothelial, HLCA_stroma, HLCA_other
    rank_genes_groups:
      reference: rest
      method: wilcoxon
    plot:
      n_genes: 10
    layer: layers/normcounts

  label_transfer:
    majority_reference:
      reference_key: manual_ann
      query_key: leiden_0.5_3
      crosstab_kwargs:
        dropna: true

  collect:
    sep: --
    same_slots:
      - X
      - var
      - layers
    merge_slots:
      - obs
      - obsm
      - obsp
      - uns
    skip_slots:
      - raw