output_dir: data/pipeline
images: data/images

os: intel
cran_url: http://cran.us.r-project.org
use_gpu: false

dataset_meta: configs/datasets.tsv
schema_file: configs/schema_mapping_tier1.tsv


defaults:

  preprocessing:
    raw_counts: X
    normalize:
      target_sum: 10_000
    highly_variable_genes:
      n_top_genes: 2000
      batch_key: dataset
      dask: false
    assemble:
      - normalize
      - highly_variable_genes
    colors:
      - dataset
      - cell_type
      - batch_integration
      - age
      - disease

  integration:
    batch: batch_integration
    label: cell_type
    raw_counts: layers/counts
    norm_counts: layers/normcounts
    var_mask: highly_variable
    output_types:
      - embed
    umap_colors:
      - assay
      - dataset
      - cell_type_reannotatedIntegrated
      - cell_subtype_beta_coarse_reannotatedIntegrated
      - cell_subtype_beta_fine_reannotatedIntegrated
      - cell_subtype_endothelial_reannotatedIntegrated
      - cell_subtype_immune_reannotatedIntegrated
      - cell_type_originalDataset_unified
      - majority_reference
      - qc_status
      - age
      - sex
      - disease
      - scrublet_score
      - n_genes
      - n_counts
      - percent_mito
    methods:
      unintegrated:
      harmony_pytorch:
        n_comps: 50
        scale: true
      scvi:
        n_latent: 30
        encode_covariates: True
        deeply_inject_covariates: False
        use_layer_norm: both
        use_batch_norm: none
        gene_likelihood: nb
        max_epochs: 20
        early_stopping: true
      # scanvi:
      #   n_latent: 30
      #   encode_covariates: True
      #   deeply_inject_covariates: False
      #   use_layer_norm: both
      #   use_batch_norm: none
      #   gene_likelihood: nb
      #   max_epochs: 20
      #   early_stopping: true
      # drvi:
      #   n_latent: 30
      #   encoder_dims:
      #     - [128, 128]
      #   decoder_dims:
      #     - [128, 128]
      #   max_epochs: 20
      #   early_stopping: true
      # scpoli:
      #   embedding_dims: 128
      #   recon_loss: nb
      #   n_epochs: 20
      #   unlabeled_prototype_training: false
      #   eta: 0.3

  clustering:
    algorithm: leiden
    use_gpu: false
    neighbors:
      use_rep: X_emb
    resolutions:
      - 0.5
    hierarchy:
      2: 0.2
      3: 0.5
    umap_colors:
      - assay
      - dataset
      - cell_type_reannotatedIntegrated
      # - cell_subtype_beta_coarse_reannotatedIntegrated
      # - cell_subtype_beta_fine_reannotatedIntegrated
      # - cell_subtype_endothelial_reannotatedIntegrated
      # - cell_subtype_immune_reannotatedIntegrated
      - cell_type_originalDataset_unified
      # - majority_reference
      - qc_status
      - age
      - sex
      - disease
      - scrublet_score
      - n_genes
      - n_counts
      - percent_mito

  metrics:
    unintegrated: layers/normcounts
    raw_counts: layers/counts
    var_mask: highly_variable
    overwrite_file_id: true
    weight_batch: 0.4
    label: cell_type_originalDataset_unified
    batch: batch_integration
    covariates:
      - age
      - diabetes_model
    gene_sets: MIA
    metrics:
      - nmi
      - ari
      # - asw_label
      # - asw_batch
      - cell_cycle
      - clisi
      - ilisi
      - graph_connectivity
      - isolated_label_f1
      - pcr_comparison
      - morans_i_genes
      # - pcr
      # - pcr_genes
      - kbet_pg
  
  marker_genes:
    sample: dataset__design__sample
    groups:
      # - majority_reference
      - cell_type_reannotatedIntegrated
      - leiden_0.5_2
    marker_genes: MIA
    rank_genes_groups:
      reference: rest
      method: wilcoxon
    plot:
      n_genes: 10
    layer: layers/normcounts

  label_transfer:
    majority_reference:
      reference_key: cell_type_reannotatedIntegrated
      query_key: leiden_0.5_3
      crosstab_kwargs:
        dropna: true

  collect:
    sep: --
    same_slots:
      - X
      - var
      - layers
    merge_slots:
      - obs
      - obsm
      - obsp
      - uns
    skip_slots:
      - raw
  
  majority_voting:
    columns:
      - majority_reference--.*
